// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v1.0.0
// source: github.com/kralicky/totem/extensions.proto

package totem

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReplicationStrategy int32

const (
	ReplicationStrategy_First     ReplicationStrategy = 0
	ReplicationStrategy_Broadcast ReplicationStrategy = 1
)

// Enum value maps for ReplicationStrategy.
var (
	ReplicationStrategy_name = map[int32]string{
		0: "First",
		1: "Broadcast",
	}
	ReplicationStrategy_value = map[string]int32{
		"First":     0,
		"Broadcast": 1,
	}
)

func (x ReplicationStrategy) Enum() *ReplicationStrategy {
	p := new(ReplicationStrategy)
	*p = x
	return p
}

func (x ReplicationStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReplicationStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_kralicky_totem_extensions_proto_enumTypes[0].Descriptor()
}

func (ReplicationStrategy) Type() protoreflect.EnumType {
	return &file_github_com_kralicky_totem_extensions_proto_enumTypes[0]
}

func (x ReplicationStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReplicationStrategy.Descriptor instead.
func (ReplicationStrategy) EnumDescriptor() ([]byte, []int) {
	return file_github_com_kralicky_totem_extensions_proto_rawDescGZIP(), []int{0}
}

type QOS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReplicationStrategy ReplicationStrategy `protobuf:"varint,1,opt,name=replicationStrategy,proto3,enum=totem.ReplicationStrategy" json:"replicationStrategy,omitempty"`
}

func (x *QOS) Reset() {
	*x = QOS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kralicky_totem_extensions_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QOS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QOS) ProtoMessage() {}

func (x *QOS) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kralicky_totem_extensions_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QOS.ProtoReflect.Descriptor instead.
func (*QOS) Descriptor() ([]byte, []int) {
	return file_github_com_kralicky_totem_extensions_proto_rawDescGZIP(), []int{0}
}

func (x *QOS) GetReplicationStrategy() ReplicationStrategy {
	if x != nil {
		return x.ReplicationStrategy
	}
	return ReplicationStrategy_First
}

var file_github_com_kralicky_totem_extensions_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*QOS)(nil),
		Field:         10001,
		Name:          "totem.qos",
		Tag:           "bytes,10001,opt,name=qos",
		Filename:      "github.com/kralicky/totem/extensions.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional totem.QOS qos = 10001;
	E_Qos = &file_github_com_kralicky_totem_extensions_proto_extTypes[0]
)

var File_github_com_kralicky_totem_extensions_proto protoreflect.FileDescriptor

var file_github_com_kralicky_totem_extensions_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x72, 0x61,
	0x6c, 0x69, 0x63, 0x6b, 0x79, 0x2f, 0x74, 0x6f, 0x74, 0x65, 0x6d, 0x2f, 0x65, 0x78, 0x74, 0x65,
	0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74, 0x6f,
	0x74, 0x65, 0x6d, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x53, 0x0a, 0x03, 0x51, 0x4f, 0x53, 0x12, 0x4c, 0x0a, 0x13,
	0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x61, 0x74,
	0x65, 0x67, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x74, 0x6f, 0x74, 0x65,
	0x6d, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x72,
	0x61, 0x74, 0x65, 0x67, 0x79, 0x52, 0x13, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x2a, 0x2f, 0x0a, 0x13, 0x52, 0x65,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67,
	0x79, 0x12, 0x09, 0x0a, 0x05, 0x46, 0x69, 0x72, 0x73, 0x74, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09,
	0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x10, 0x01, 0x3a, 0x3d, 0x0a, 0x03, 0x71,
	0x6f, 0x73, 0x12, 0x1e, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x91, 0x4e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x74, 0x6f, 0x74, 0x65,
	0x6d, 0x2e, 0x51, 0x4f, 0x53, 0x52, 0x03, 0x71, 0x6f, 0x73, 0x42, 0x1b, 0x5a, 0x19, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x72, 0x61, 0x6c, 0x69, 0x63, 0x6b,
	0x79, 0x2f, 0x74, 0x6f, 0x74, 0x65, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_github_com_kralicky_totem_extensions_proto_rawDescOnce sync.Once
	file_github_com_kralicky_totem_extensions_proto_rawDescData = file_github_com_kralicky_totem_extensions_proto_rawDesc
)

func file_github_com_kralicky_totem_extensions_proto_rawDescGZIP() []byte {
	file_github_com_kralicky_totem_extensions_proto_rawDescOnce.Do(func() {
		file_github_com_kralicky_totem_extensions_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_kralicky_totem_extensions_proto_rawDescData)
	})
	return file_github_com_kralicky_totem_extensions_proto_rawDescData
}

var file_github_com_kralicky_totem_extensions_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_github_com_kralicky_totem_extensions_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_github_com_kralicky_totem_extensions_proto_goTypes = []interface{}{
	(ReplicationStrategy)(0),           // 0: totem.ReplicationStrategy
	(*QOS)(nil),                        // 1: totem.QOS
	(*descriptorpb.MethodOptions)(nil), // 2: google.protobuf.MethodOptions
}
var file_github_com_kralicky_totem_extensions_proto_depIdxs = []int32{
	0, // 0: totem.QOS.replicationStrategy:type_name -> totem.ReplicationStrategy
	2, // 1: totem.qos:extendee -> google.protobuf.MethodOptions
	1, // 2: totem.qos:type_name -> totem.QOS
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	2, // [2:3] is the sub-list for extension type_name
	1, // [1:2] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_github_com_kralicky_totem_extensions_proto_init() }
func file_github_com_kralicky_totem_extensions_proto_init() {
	if File_github_com_kralicky_totem_extensions_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_kralicky_totem_extensions_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QOS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_kralicky_totem_extensions_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_github_com_kralicky_totem_extensions_proto_goTypes,
		DependencyIndexes: file_github_com_kralicky_totem_extensions_proto_depIdxs,
		EnumInfos:         file_github_com_kralicky_totem_extensions_proto_enumTypes,
		MessageInfos:      file_github_com_kralicky_totem_extensions_proto_msgTypes,
		ExtensionInfos:    file_github_com_kralicky_totem_extensions_proto_extTypes,
	}.Build()
	File_github_com_kralicky_totem_extensions_proto = out.File
	file_github_com_kralicky_totem_extensions_proto_rawDesc = nil
	file_github_com_kralicky_totem_extensions_proto_goTypes = nil
	file_github_com_kralicky_totem_extensions_proto_depIdxs = nil
}
