// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	ragù          v0.1.0
// source: totem.proto

package totem

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RPC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag    uint64 `protobuf:"varint,1,opt,name=Tag,proto3" json:"Tag,omitempty"`
	Method string `protobuf:"bytes,2,opt,name=Method,proto3" json:"Method,omitempty"`
	// Types that are assignable to Content:
	//	*RPC_Request
	//	*RPC_Response
	Content isRPC_Content `protobuf_oneof:"Content"`
}

func (x *RPC) Reset() {
	*x = RPC{}
	if protoimpl.UnsafeEnabled {
		mi := &file_totem_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPC) ProtoMessage() {}

func (x *RPC) ProtoReflect() protoreflect.Message {
	mi := &file_totem_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPC.ProtoReflect.Descriptor instead.
func (*RPC) Descriptor() ([]byte, []int) {
	return file_totem_proto_rawDescGZIP(), []int{0}
}

func (x *RPC) GetTag() uint64 {
	if x != nil {
		return x.Tag
	}
	return 0
}

func (x *RPC) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (m *RPC) GetContent() isRPC_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (x *RPC) GetRequest() []byte {
	if x, ok := x.GetContent().(*RPC_Request); ok {
		return x.Request
	}
	return nil
}

func (x *RPC) GetResponse() *Response {
	if x, ok := x.GetContent().(*RPC_Response); ok {
		return x.Response
	}
	return nil
}

type isRPC_Content interface {
	isRPC_Content()
}

type RPC_Request struct {
	Request []byte `protobuf:"bytes,3,opt,name=Request,proto3,oneof"`
}

type RPC_Response struct {
	Response *Response `protobuf:"bytes,4,opt,name=Response,proto3,oneof"`
}

func (*RPC_Request) isRPC_Content() {}

func (*RPC_Response) isRPC_Content() {}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response []byte `protobuf:"bytes,1,opt,name=Response,proto3" json:"Response,omitempty"`
	Error    []byte `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_totem_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_totem_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_totem_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetResponse() []byte {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *Response) GetError() []byte {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_totem_proto protoreflect.FileDescriptor

var file_totem_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74,
	0x6f, 0x74, 0x65, 0x6d, 0x22, 0x71, 0x0a, 0x03, 0x52, 0x50, 0x43, 0x12, 0x0d, 0x0a, 0x03, 0x54,
	0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x42, 0x00, 0x12, 0x10, 0x0a, 0x06, 0x4d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x00, 0x12, 0x13, 0x0a, 0x07,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x42, 0x00, 0x48,
	0x00, 0x12, 0x25, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x6f, 0x74, 0x65, 0x6d, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x00, 0x48, 0x00, 0x3a, 0x00, 0x42, 0x0b, 0x0a, 0x07, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x00, 0x22, 0x31, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x42, 0x00, 0x12, 0x0f, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x42, 0x00, 0x3a, 0x00, 0x42, 0x1b, 0x5a, 0x19, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x72, 0x61, 0x6c, 0x69, 0x63, 0x6b,
	0x79, 0x2f, 0x74, 0x6f, 0x74, 0x65, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_totem_proto_rawDescOnce sync.Once
	file_totem_proto_rawDescData = file_totem_proto_rawDesc
)

func file_totem_proto_rawDescGZIP() []byte {
	file_totem_proto_rawDescOnce.Do(func() {
		file_totem_proto_rawDescData = protoimpl.X.CompressGZIP(file_totem_proto_rawDescData)
	})
	return file_totem_proto_rawDescData
}

var file_totem_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_totem_proto_goTypes = []interface{}{
	(*RPC)(nil),      // 0: totem.RPC
	(*Response)(nil), // 1: totem.Response
}
var file_totem_proto_depIdxs = []int32{
	1, // 0: totem.RPC.Response:type_name -> totem.Response
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_totem_proto_init() }
func file_totem_proto_init() {
	if File_totem_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_totem_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RPC); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_totem_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_totem_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*RPC_Request)(nil),
		(*RPC_Response)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_totem_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_totem_proto_goTypes,
		DependencyIndexes: file_totem_proto_depIdxs,
		MessageInfos:      file_totem_proto_msgTypes,
	}.Build()
	File_totem_proto = out.File
	file_totem_proto_rawDesc = nil
	file_totem_proto_goTypes = nil
	file_totem_proto_depIdxs = nil
}
