// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	ragù          v0.2.3
// source: totem.proto

package totem

import (
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RPC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag    uint64 `protobuf:"varint,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Method string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	// Types that are assignable to Content:
	//	*RPC_Request
	//	*RPC_Response
	Content  isRPC_Content `protobuf_oneof:"content"`
	Metadata *MD           `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *RPC) Reset() {
	*x = RPC{}
	if protoimpl.UnsafeEnabled {
		mi := &file_totem_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPC) ProtoMessage() {}

func (x *RPC) ProtoReflect() protoreflect.Message {
	mi := &file_totem_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPC.ProtoReflect.Descriptor instead.
func (*RPC) Descriptor() ([]byte, []int) {
	return file_totem_proto_rawDescGZIP(), []int{0}
}

func (x *RPC) GetTag() uint64 {
	if x != nil {
		return x.Tag
	}
	return 0
}

func (x *RPC) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (m *RPC) GetContent() isRPC_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (x *RPC) GetRequest() []byte {
	if x, ok := x.GetContent().(*RPC_Request); ok {
		return x.Request
	}
	return nil
}

func (x *RPC) GetResponse() *Response {
	if x, ok := x.GetContent().(*RPC_Response); ok {
		return x.Response
	}
	return nil
}

func (x *RPC) GetMetadata() *MD {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type isRPC_Content interface {
	isRPC_Content()
}

type RPC_Request struct {
	Request []byte `protobuf:"bytes,3,opt,name=request,proto3,oneof"`
}

type RPC_Response struct {
	Response *Response `protobuf:"bytes,4,opt,name=response,proto3,oneof"`
}

func (*RPC_Request) isRPC_Content() {}

func (*RPC_Response) isRPC_Content() {}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response    []byte         `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	StatusProto *status.Status `protobuf:"bytes,2,opt,name=statusProto,proto3" json:"statusProto,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_totem_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_totem_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_totem_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetResponse() []byte {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *Response) GetStatusProto() *status.Status {
	if x != nil {
		return x.StatusProto
	}
	return nil
}

type MD struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data map[string]*MDValues `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *MD) Reset() {
	*x = MD{}
	if protoimpl.UnsafeEnabled {
		mi := &file_totem_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MD) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MD) ProtoMessage() {}

func (x *MD) ProtoReflect() protoreflect.Message {
	mi := &file_totem_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MD.ProtoReflect.Descriptor instead.
func (*MD) Descriptor() ([]byte, []int) {
	return file_totem_proto_rawDescGZIP(), []int{2}
}

func (x *MD) GetData() map[string]*MDValues {
	if x != nil {
		return x.Data
	}
	return nil
}

type MDValues struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []string `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *MDValues) Reset() {
	*x = MDValues{}
	if protoimpl.UnsafeEnabled {
		mi := &file_totem_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MDValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MDValues) ProtoMessage() {}

func (x *MDValues) ProtoReflect() protoreflect.Message {
	mi := &file_totem_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MDValues.ProtoReflect.Descriptor instead.
func (*MDValues) Descriptor() ([]byte, []int) {
	return file_totem_proto_rawDescGZIP(), []int{3}
}

func (x *MDValues) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_totem_proto protoreflect.FileDescriptor

var file_totem_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74,
	0x6f, 0x74, 0x65, 0x6d, 0x1a, 0x17, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x72, 0x70, 0x63,
	0x2f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x90, 0x01,
	0x0a, 0x03, 0x52, 0x50, 0x43, 0x12, 0x0d, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x42, 0x00, 0x12, 0x10, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x42, 0x00, 0x12, 0x13, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x42, 0x00, 0x48, 0x00, 0x12, 0x25, 0x0a, 0x08, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x74, 0x6f, 0x74, 0x65, 0x6d, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x00,
	0x48, 0x00, 0x12, 0x1d, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x74, 0x6f, 0x74, 0x65, 0x6d, 0x2e, 0x4d, 0x44, 0x42,
	0x00, 0x3a, 0x00, 0x42, 0x0b, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x00,
	0x22, 0x4b, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x08,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x42, 0x00,
	0x12, 0x29, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x00, 0x3a, 0x00, 0x22, 0x73, 0x0a,
	0x02, 0x4d, 0x44, 0x12, 0x21, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x74, 0x6f, 0x74, 0x65, 0x6d, 0x2e, 0x4d, 0x44, 0x2e, 0x44, 0x61, 0x74,
	0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x1a, 0x48, 0x0a, 0x09, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x25, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x6f, 0x74, 0x65, 0x6d, 0x2e, 0x4d, 0x44, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x3a, 0x00, 0x22, 0x1d, 0x0a, 0x08, 0x4d, 0x44, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x0f,
	0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x42, 0x00, 0x3a,
	0x00, 0x42, 0x1b, 0x5a, 0x19, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6b, 0x72, 0x61, 0x6c, 0x69, 0x63, 0x6b, 0x79, 0x2f, 0x74, 0x6f, 0x74, 0x65, 0x6d, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_totem_proto_rawDescOnce sync.Once
	file_totem_proto_rawDescData = file_totem_proto_rawDesc
)

func file_totem_proto_rawDescGZIP() []byte {
	file_totem_proto_rawDescOnce.Do(func() {
		file_totem_proto_rawDescData = protoimpl.X.CompressGZIP(file_totem_proto_rawDescData)
	})
	return file_totem_proto_rawDescData
}

var file_totem_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_totem_proto_goTypes = []interface{}{
	(*RPC)(nil),           // 0: totem.RPC
	(*Response)(nil),      // 1: totem.Response
	(*MD)(nil),            // 2: totem.MD
	(*MDValues)(nil),      // 3: totem.MDValues
	nil,                   // 4: totem.MD.DataEntry
	(*status.Status)(nil), // 5: google.rpc.Status
}
var file_totem_proto_depIdxs = []int32{
	1, // 0: totem.RPC.response:type_name -> totem.Response
	2, // 1: totem.RPC.metadata:type_name -> totem.MD
	5, // 2: totem.Response.statusProto:type_name -> google.rpc.Status
	4, // 3: totem.MD.data:type_name -> totem.MD.DataEntry
	3, // 4: totem.MD.DataEntry.value:type_name -> totem.MDValues
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_totem_proto_init() }
func file_totem_proto_init() {
	if File_totem_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_totem_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RPC); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_totem_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_totem_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MD); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_totem_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MDValues); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_totem_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*RPC_Request)(nil),
		(*RPC_Response)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_totem_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_totem_proto_goTypes,
		DependencyIndexes: file_totem_proto_depIdxs,
		MessageInfos:      file_totem_proto_msgTypes,
	}.Build()
	File_totem_proto = out.File
	file_totem_proto_rawDesc = nil
	file_totem_proto_goTypes = nil
	file_totem_proto_depIdxs = nil
}
